apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: test
  annotations:
    meta.crossplane.io/maintainer: test
    meta.crossplane.io/source: test
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      use secret as input for composition
    meta.crossplane.io/readme: |
      use secret as input for composition
spec:
  crossplane:
    version: ">=v1.12.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-nop
      version: ">=v0.2.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.9.0"
    - provider: xpkg.upbound.io/upbound/provider-upbound
      version: ">=v0.2.0"